#ifndef __UDC_ENUM_H__
#define __UDC_ENUM_H__

#ifdef __cplusplus
export "C" {
#endif


typedef enum
{
	UDC_EVENT_CODE_UNKNOWN = -1,
	UDC_EVENT_CODE_BOOT,
	UDC_EVENT_CODE_RATINGS,
	UDC_EVENT_CODE_HEARTBEAT,
	UDC_EVENT_CODE_ALARM,
	UDC_EVENT_CODE_INFORM,
	UDC_EVENT_CODE_MAX,
}UDC_EVENT_CODE_e;

typedef enum
{
	UDC_ALARM_EVENT_CODE_UNKNOWN = -1,
	UDC_ALARM_EVENT_CODE_SIGNALQUALITY,
	UDC_ALARM_EVENT_CODE_FRAMESLOST,
	UDC_ALARM_EVENT_CODE_PACKETSLOST,
	UDC_ALARM_EVENT_CODE_MAX,
}UDC_ALARM_EVENT_CODE_e;

typedef enum
{
	UDC_RPC_EVENT_CODE_UNKNOWN = -1,
	UDC_RPC_EVENT_CODE_SPECTRUM,
	UDC_RPC_EVENT_CODE_IPADDRESS,
	UDC_RPC_EVENT_CODE_SUBNETMASK,
	UDC_RPC_EVENT_CODE_MACADDRESS,
	UDC_RPC_EVENT_CODE_REGION,
	UDC_RPC_EVENT_CODE_MAX,
}UDC_RPC_EVENT_CODE_e;

typedef enum
{
	UDC_WATCH_TYPE_UNKNOWN = -1,
	UDC_WATCH_TYPE_TV,
	UDC_WATCH_TYPE_BROADCAST,
	UDC_WATCH_TYPE_OTHER,
	UDC_WATCH_TYPE_MAX,
}UDC_WATCH_TYPE_e;

typedef enum
{
	UDC_SERVER_ERROR_CODE_UNKNOWN = -1,
	UDC_SERVER_ERROR_CODE_NOERROR,
	UDC_SERVER_ERROR_CODE_ERROR,
}UDC_SERVER_ERROR_CODE_e;


#ifdef __cplusplus
}
#endif
#endif